# Generated by Django 4.2.5 on 2023-12-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
