# Generated by Django 4.2.5 on 2023-12-31 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_alter_post_options_remove_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.FileField(default='comment-image/user.jpg', upload_to='comment-image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post_app.comment'),
            preserve_default=False,
        ),
    ]
