# Generated by Django 4.2.5 on 2023-12-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_comment_image_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
