# Generated by Django 4.2.5 on 2023-12-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
