# Generated by Django 4.2.5 on 2023-12-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_alter_comment_image_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
