# Generated by Django 4.2.5 on 2024-01-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0013_comment_image_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
