# Generated by Django 4.2.5 on 2024-01-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0014_remove_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.FileField(default='comment-image/user.jpg', upload_to='comment-image'),
        ),
    ]
