# Generated by Django 4.2.5 on 2024-01-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0015_remove_comment_parent_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(default='comment_image/user.jpg', upload_to='comment_image'),
        ),
    ]
